postgres.address=postgresPrimary:5432
postgres.readonly.address=postgresSecondary:5431

knime.artemis.url=tcp://broker:61616?reconnectAttempts=-1

opa.url=http://opa:8181

quarkus.rest-client."knime.artifacts".url=http://artifacts-service:8080/artifacts/data-sources/catalog
knime.catalog.object-store.url=http://minio:9000

# userdata.service.url=http://localhost:9020
# quarkus.otel.exporter.otlp.traces.endpoint=http://localhost:4317